version: "3"

networks:
  web:
    external: true

services:
  api:
    build: ./cage-api
    image: cage-api:latest
    restart: always

    environment:
      - "MONGODB=mongodb+srv://romp:GearCrypt0@gearcrypt0.mo1qvtz.mongodb.net/cage?retryWrites=true&w=majority"
      - "JWT_SECRET=INSERT_SECRET_HERE"
      - "JWT_EXPIRE=1200s"

    labels:
      - "treafik.enable=true"
      - "traefik.http.routers.cage-api.entrypoints=http"
      - "traefik.http.routers.cage-api.rule=Host(`api.cage.romplabs.com`)"
      - "traefik.http.services.cage-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

    networks:
      - web

  app:
    build: ./cage-app
    image: cage-app:latest
    restart: always
    depends_on:
      - "api"
    environment:
      - "API=http://api.cage.romplabs.com/"
      - "NEXTAUTH_URL=http://cage.romplabs.com/"
      - "NEXTAUTH_SECRET=E6i0Oxk2KJ1VjUeUyCdeuz0ZR3ZH5LtFSnrZv8huuj8=="
    labels:
      - "treafik.enable=true"
      - "traefik.http.routers.cage-app.entrypoints=http"
      - "traefik.http.routers.cage-app.rule=Host(`cage.romplabs.com`)"
      - "traefik.http.services.cage-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

    networks:
      - web
